version: "3.7"
services:
  db:
    # Dockerfileの相対Path
    build: docker/db/
    # 環境変数としてパスワードを設定
    environment:
      MYSQL_ROOT_PASSWORD: password
    # データの保存場所を設定
    volumes:
      - "mysql-data:/var/lib/mysql"
    # macのポート3306としてdbコンテナのポートを繋げる
    ports:
      - "3306:3306"
    # mysqlのパスワードの暗号化をRailsで参照出来る形式に変更
    command: mysqld --default-authentication-plugin=mysql_native_password
volumes:
  mysql-data:
    driver: local